build:
  version: "1.1"

app:
  message: "Welcome to Corelate Application Builder "
  contactDetails:
    name: "Seth Hernandez - Developer"
    email: "seth.hernandez@corelate.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
